package com.vantedge.app.domain

object PipelineEvents {
    const val TRYCHAIN_START = "TRYCHAIN_START"
    const val ATTEMPT_START = "ATTEMPT_START"
    const val HTTP_REQUEST_BEGIN = "HTTP_REQUEST_BEGIN"
    const val HTTP_RESPONSE_RECEIVED = "HTTP_RESPONSE_RECEIVED"
    const val HTTP_REQUEST_FAILED = "HTTP_REQUEST_FAILED"
    const val WITH_TIMEOUT_EXIT = "WITH_TIMEOUT_EXIT"
    const val ATTEMPT_END = "ATTEMPT_END"
    const val TRYCHAIN_END = "TRYCHAIN_END"
    const val FINAL_RETRY_BEGIN = "FINAL_RETRY_BEGIN"
    const val FINAL_RETRY_END = "FINAL_RETRY_END"
    const val RAW_RESPONSE_CAPTURED = "RAW_RESPONSE_CAPTURED"
    const val RAW_RESPONSE_ARTIFACT = "RAW_RESPONSE_ARTIFACT"
    const val CIRCUIT_BREAKER_SKIP = "CIRCUIT_BREAKER_SKIP"
    const val CIRCUIT_BREAKER_RESET = "CIRCUIT_BREAKER_RESET"
    const val CIRCUIT_BREAKER_DEGRADE = "CIRCUIT_BREAKER_DEGRADE"
    const val EXTRACTION_RESULT = "EXTRACTION_RESULT"
    const val PARSE_RESULT = "PARSE_RESULT"
    const val VALIDATION_RESULT = "VALIDATION_RESULT"
}
