package com.vantedge.app.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CoverLetterScreen(
    onNavigateBack: () -> Unit,
    onOpenPreview: (String, String) -> Unit
) {

    var jobDescription by remember { mutableStateOf("") }
    var generated by remember { mutableStateOf("") }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("AI Cover Letter") },
                navigationIcon = {
                    IconButton(onClick = onNavigateBack) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Back")
                    }
                }
            )
        }
    ) { padding ->

        Column(
            modifier = Modifier
                .padding(padding)
                .fillMaxSize()
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {

            OutlinedTextField(
                value = jobDescription,
                onValueChange = { jobDescription = it },
                modifier = Modifier.fillMaxWidth(),
                placeholder = { Text("Paste job description") }
            )

            Button(
                onClick = {
                    generated = "Cover letter generated for: $jobDescription"
                },
                modifier = Modifier.fillMaxWidth()
            ) {
                Text("Generate")
            }

            if (generated.isNotEmpty()) {
                Text(generated)

                Button(
                    onClick = {
                        onOpenPreview(generated, "CoverLetter")
                    }
                ) {
                    Text("Preview")
                }
            }
        }
    }
}